### ISSUE TITLE
Download body motion from the json file

### ISSUE THREAD

**Issue by jiaoc1** [facebookresearch/nymeria_dataset#7]
In the download_urls.json, the key for body motion is "body_motion". It doesn't match the DataGroups name "body" in line 126 in the definition.py. Therefore, the DownloadManager cannot find the download link in line 223 in download_utils.py. Could you please either update the DataGroups by changing the "body" to "body_motion" or update the "body_motion" to "body" in the json file to fix the issue?

**Comment by SummerIcequeen** [comment]
Thanks for raising the issue. It should be fixed now! Please pull the latest master.
